// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

type User struct {
    Id    string
    Name  string
    Email string
}

type GetUserRequest struct {
    Id string
}

type GetUserResponse struct {
    User *User
}

type ListUsersRequest struct {
    PageSize  int32
    PageToken string
}

type ListUsersResponse struct {
    Users         []*User
    NextPageToken string
}
